var allowedDomains = ['susdude.dev'];

if (allowedDomains.indexOf(document.domain) == -1) {
  window.location.href = "https://susdude.dev/games/buttonclicker/redirect"
}
alert(document.domain)
document.write('<!DOCTYPE html>');
document.write('<html>');
document.write('  <head>');
document.write('    <meta charset="utf-8">');
document.write('    <meta name="viewport" content="width=device-width">');
document.write('    <style>');
document.write('button {');
document.write('  background-color: blue; ');
document.write('  color: orange;');
document.write('}');
document.write('    </style>');
document.write('    <title>The sussiest site</title>');
document.write('  </head>');
document.write('  <body style="background-color: orange;">');
document.write('    <h1 style="color: blue;">Button Clicker</h1>');
document.write('    <p style=" color: blue;">Click the Score to get points, click add to multi or add one rebirth to preform actions, saves as cookies, project of mine so i can mess with cookies</p>');
document.write('    <button id="b" onclick="addscore()">0</button>');
document.write('    <button onclick="addmulti()" id="mb">Add 0.1 to multi (Cost 200)</button>');
document.write('   <button onclick="Rebirth()" id="rb">Set Multi And score to 1, Add 1 rebirth (Cost 3000)</button>');
document.write('   <button onclick="addcps()" id="cb">Click Once every 1 second (Cost 1000)</button>');
document.write('    <p style="color: blue;">Multi: <span id="mc">0</span></p>');
document.write('    <p style="color: blue;">Rebirth: <span id="rc">0</span></p>');
document.write('    <p style="color: blue;">Clickers: <span id="cc">0</span></p>');
document.write('    <script>      function cheat(type) {');
document.write('        if (type == "set") {');
document.write('        score = parseInt(prompt("Score"))');
document.write('        b.innerHTML = "Score: " + score.toString()');
document.write('        document.cookie = "score=" + score;');
document.write('        }');
document.write('        if (type == "add") {');
document.write('        score += parseInt(prompt("Score"))');
document.write('        b.innerHTML = "Score: " + score.toString()');
document.write('        document.cookie = "score=" + score;');
document.write('        }');
document.write('        if (type == "setm") {');
document.write('        mult = parseInt(prompt("Multiplier"))');
document.write('        mc.innerHTML = mult.toString()');
document.write('        document.cookie = "mult=" + mult;');
document.write('        }');
document.write('        if (type == "addm") {');
document.write('        mult += parseInt(prompt("Multiplier"))');
document.write('        mc.innerHTML = mult.toString()');
document.write('        document.cookie = "mult=" + mult;');
document.write('        }');
document.write('        if (type == "setr") {');
document.write('        r = parseInt(prompt("Rebirth"))');
document.write('        rc.innerHTML = r.toString()');
document.write('        document.cookie = "r=" + r;');
document.write('        }');
document.write('        if (type == "addr") {');
document.write('        r += parseInt(prompt("Rebirth"))');
document.write('        rc.innerHTML = r.toString()');
document.write('        document.cookie = "r=" + r;');
document.write('        }');
document.write('      }</script>');
document.write('    <script src="js/stats.js"></script>');
document.write('    <script src="js/score.js"></script>');
document.write('  </body>');
document.write('</html>');
